# Introduction to Python

In [60]:
# Calculator
a = (50 + 1.45) / 12.5 # (CTRL + ENTER)
b = "hello" + " " + "world"

# print
print(a)
print(b)

4.1160000000000005
hello world


In [61]:
# Lists
x = [3, "hello", [3, 4]]
y = [1, 2, 3]
print(x + y)

[3, 'hello', [3, 4], 1, 2, 3]


In [62]:
# Flow control
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [63]:
for i in x:
    print(i)

3
hello
[3, 4]


In [64]:
i = 0
while i < 10:
    print(i)
    i += 1

0
1
2
3
4
5
6
7
8
9


In [65]:
# Functions
def plus(a, b):
    return a + b

plus(1, 2)

3

## Numpy

In [66]:
# Install library (Jupyter 7.3 or later)
# %pip install numpy  

In [67]:
# Older versions
# import sys
# !{sys.executable} -m pip install numpy

In [68]:
# Import library
import numpy as np

In [69]:
# Numpy arrays
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

print(x)
print(y)

[3 4 5]
[4 9 7]


In [70]:
# Numpy allows mathematical operations between arrays
print(x+y)

[ 7 13 12]


In [71]:
# Different from normal lists
x = [3,4,5]
y = [4,9,7]
print(x+y)

[3, 4, 5, 4, 9, 7]


In [72]:
# 2-dimensional arrays

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(a*b)

a.dtype

[[ 5 12]
 [21 32]]


dtype('int64')

In [73]:
# Documentation
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [74]:
# Array dimensions
print(a.ndim)    # Number of dimensions
print(a.shape)   # Shape of the array

2
(2, 2)


In [75]:
# Reshaping arrays
a = np.array([[1, 2], [3, 4]])
print(a.reshape([1,4]))  # [rows, columns]

[[1 2 3 4]]


In [76]:
c = np.array([1, 2, 3, 4, 5, 6])
print(c.reshape(2, 3))    # Convert a 1d array to a 2x3 array

[[1 2 3]
 [4 5 6]]


## Indexing Arrays

In [77]:
A = np.array(np.arange(16)).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
# Select single element

print(A[1,2]) #[row, column]
# or
print(A[1][2])

6
6


In [79]:
# Select entire row/column
print(A[0,:])    # : selects everything

print(A[0])

print(A[:,0])

[0 1 2 3]
[0 1 2 3]
[ 0  4  8 12]


In [80]:
# Select multiple rows/columns
print(A[[1, 2],:])    # 2nd and 3rd row
print(A[:, [2,3]])    # 3rd and 4th column

[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [81]:
# Select a submatrix
print(A[[0,1], [0,1]]) # Doesn't work, selects individual elements [0,0] and [1,1]

[0 5]


In [82]:
print(A[[0,1]][:,[0,1]]) # Select the rows first, then the columns

[[0 1]
 [4 5]]


In [83]:
print(A[0:2, 0:2]) # Or with slices

[[0 1]
 [4 5]]


## Boolean indexing

In [84]:
A = [0,1,2,3,4,5,6,7,8,9]
B = [True, False, True, False, True, False, True, False, True, False]

In [85]:
A[B]  # Error - This does not work with python arrays

TypeError: list indices must be integers or slices, not list

In [86]:
# With numpy arrays, we select every element, where B == True
A = np.array(A)
print(A[B])

[0 2 4 6 8]


In [87]:
# We can use boolean indexing to select elements matching specific conditions
print(A[A > 5])
print(A[A % 2 == 0])
print(A[(A > 2) & (A < 7)])

[6 7 8 9]
[0 2 4 6 8]
[3 4 5 6]


In [88]:
# Also works with n-dimensional arrays
A = np.array(np.arange(16)).reshape((4, 4))
print(A)
rows = [True, False, True, False]
cols = [True, True, False, False]
A[rows][:,cols]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[0, 1],
       [8, 9]])

In [89]:
# Select rows that sum up to more than 25
high_rows = np.sum(A, axis=1) > 25
print(high_rows)
A[high_rows]

[False False  True  True]


array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Pandas and Datasets

In [90]:
# In addition to Numpy arrays, we can use additional libraries to better process larger datasets
import pandas as pd

In [91]:
auto = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/mpg.csv')
auto

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu  
1            70     usa          buick skylark 320  
2            70     usa         plymouth satellite  
3            70     usa              amc rebel sst  
4            70     usa                ford torino  
..          ...     ...                        ...  
393          82     usa            ford mustang gl  
394          82  europe                  vw pickup  
395          82     usa              dodge rampage  
396          82     usa                ford ranger  
397          82     usa                 chevy s-10  

[398 rows x 9 columns]

## Pandas dataframes

In [92]:
# How many examples are in a dataframe
len(auto)

398

In [93]:
# Print column names
auto.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [94]:
# Are there missing values in the dataset
any(auto.isna())

True

In [95]:
# Count the missing values per column
auto.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [96]:
# Drop missing values
auto = auto.dropna()
print(len(auto))
print(auto.isna().sum())

392
mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64


In [97]:
# Drop columns
auto.drop(columns="horsepower")

mpg  cylinders  displacement  weight  acceleration  model_year  origin  \
0    18.0          8         307.0    3504          12.0          70     usa   
1    15.0          8         350.0    3693          11.5          70     usa   
2    18.0          8         318.0    3436          11.0          70     usa   
3    16.0          8         304.0    3433          12.0          70     usa   
4    17.0          8         302.0    3449          10.5          70     usa   
..    ...        ...           ...     ...           ...         ...     ...   
393  27.0          4         140.0    2790          15.6          82     usa   
394  44.0          4          97.0    2130          24.6          82  europe   
395  32.0          4         135.0    2295          11.6          82     usa   
396  28.0          4         120.0    2625          18.6          82     usa   
397  31.0          4         119.0    2720          19.4          82     usa   

                          name  
0    chevrolet chevelle malibu  
1            buick skylark 320  
2           plymouth satellite  
3                amc rebel sst  
4                  ford torino  
..                         ...  
393            ford mustang gl  
394                  vw pickup  
395              dodge rampage  
396                ford ranger  
397                 chevy s-10  

[392 rows x 8 columns]

### Indexing Pandas datasets

In [98]:
auto[1] # Error, cannot index by numbers 

KeyError: 1

In [99]:
print(auto['mpg'])  # Index by column names instead

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ... 
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 392, dtype: float64


In [100]:
print(auto[:3])     # Or use slices to select rows

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  


In [101]:
print(auto.loc[0,"mpg"]) # Or with .loc[row_numebr, column_name]

18.0


In [102]:
print(auto.iloc[0,0])    # Or with .iloc[row_number, column_number]

18.0


In [103]:
print(auto.loc[0:5, ["mpg", "cylinders"]])  # Can also select multiple rows and columns

    mpg  cylinders
0  18.0          8
1  15.0          8
2  18.0          8
3  16.0          8
4  17.0          8
5  15.0          8


We can use logical indexing to select specific rows

In [104]:
idx_80 = auto['model_year'] > 80
print(auto.loc[idx_80, ['name', 'model_year']])

                                  name  model_year
338                   plymouth reliant          81
339                      buick skylark          81
340             dodge aries wagon (sw)          81
341                 chevrolet citation          81
342                   plymouth reliant          81
343                     toyota starlet          81
344                     plymouth champ          81
345                   honda civic 1300          81
346                             subaru          81
347                     datsun 210 mpg          81
348                      toyota tercel          81
349                        mazda glc 4          81
350                 plymouth horizon 4          81
351                     ford escort 4w          81
352                     ford escort 2h          81
353                   volkswagen jetta          81
355                      honda prelude          81
356                     toyota corolla          81
357                       datsu

In [105]:
# Or in one line
print(auto.loc[auto['model_year'] > 80, ['name', 'model_year']])

                                  name  model_year
338                   plymouth reliant          81
339                      buick skylark          81
340             dodge aries wagon (sw)          81
341                 chevrolet citation          81
342                   plymouth reliant          81
343                     toyota starlet          81
344                     plymouth champ          81
345                   honda civic 1300          81
346                             subaru          81
347                     datsun 210 mpg          81
348                      toyota tercel          81
349                        mazda glc 4          81
350                 plymouth horizon 4          81
351                     ford escort 4w          81
352                     ford escort 2h          81
353                   volkswagen jetta          81
355                      honda prelude          81
356                     toyota corolla          81
357                       datsu

## Adding values

In [106]:
# Create new column
auto['Horsepower / Weight'] = auto['horsepower'] / auto['weight']
auto

C:\Users\alesz\AppData\Local\Temp\ipykernel_22788\3064049078.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  auto['Horsepower / Weight'] = auto['horsepower'] / auto['weight']


mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  Horsepower / Weight  
0            70     usa  chevrolet chevelle malibu             0.037100  
1            70     usa          buick skylark 320             0.044679  
2            70     usa         plymouth satellite             0.043655  
3            70     usa              amc rebel sst             0.043694  
4            70     usa                ford torino             0.040591  
..          ...     ...                        ...                  ...  
393          82     usa            ford mustang gl             0.030824  
394          82  europe                  vw pickup             0.024413  
395          82     usa              dodge rampage             0.036601  
396          82     usa                ford ranger             0.030095  
397          82     usa                 chevy s-10             0.030147  

[392 rows x 10 columns]

In [107]:
# Create a new empty row as a pd.Series
new_row = pd.Series([None]*10, index=['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
                                      'acceleration', 'model_year', 'origin', 'name', 'Horsepower / Weight'])

# Concatenate the new empty row with the original DataFrame
result = pd.concat([auto, new_row.to_frame().T], ignore_index=True)
result

C:\Users\alesz\AppData\Local\Temp\ipykernel_22788\3176085962.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result = pd.concat([auto, new_row.to_frame().T], ignore_index=True)


mpg cylinders  displacement  horsepower weight  acceleration model_year  \
0    18.0         8         307.0       130.0   3504          12.0         70   
1    15.0         8         350.0       165.0   3693          11.5         70   
2    18.0         8         318.0       150.0   3436          11.0         70   
3    16.0         8         304.0       150.0   3433          12.0         70   
4    17.0         8         302.0       140.0   3449          10.5         70   
..    ...       ...           ...         ...    ...           ...        ...   
388  44.0         4          97.0        52.0   2130          24.6         82   
389  32.0         4         135.0        84.0   2295          11.6         82   
390  28.0         4         120.0        79.0   2625          18.6         82   
391  31.0         4         119.0        82.0   2720          19.4         82   
392   NaN      None           NaN         NaN   None           NaN       None   

     origin                       name  Horsepower / Weight  
0       usa  chevrolet chevelle malibu             0.037100  
1       usa          buick skylark 320             0.044679  
2       usa         plymouth satellite             0.043655  
3       usa              amc rebel sst             0.043694  
4       usa                ford torino             0.040591  
..      ...                        ...                  ...  
388  europe                  vw pickup             0.024413  
389     usa              dodge rampage             0.036601  
390     usa                ford ranger             0.030095  
391     usa                 chevy s-10             0.030147  
392    None                       None                  NaN  

[393 rows x 10 columns]

## Additional functions

In [108]:
# Merge datasets
pd.concat([auto, auto])

# This can also be used to add new rows - simply create a new dataframe and concat it to the original

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  Horsepower / Weight  
0            70     usa  chevrolet chevelle malibu             0.037100  
1            70     usa          buick skylark 320             0.044679  
2            70     usa         plymouth satellite             0.043655  
3            70     usa              amc rebel sst             0.043694  
4            70     usa                ford torino             0.040591  
..          ...     ...                        ...                  ...  
393          82     usa            ford mustang gl             0.030824  
394          82  europe                  vw pickup             0.024413  
395          82     usa              dodge rampage             0.036601  
396          82     usa                ford ranger             0.030095  
397          82     usa                 chevy s-10             0.030147  

[784 rows x 10 columns]

In [109]:
# Save dataset
auto.to_csv('./is_lab_1_dataset.txt', index=False)